version: 0.1

phases:
  install:
    commands:
      - go get github.com/Masterminds/glide
  pre_build:
    commands:
      - glide up
      - mkdir -p /go/src/github.com/reiki4040/rnbin
      - mv * /go/src/github.com/reiki4040/rnbin/
      - mv .git /go/src/github.com/reiki4040/rnbin/
  build:
    commands:
      - cd /go/src/github.com/reiki4040/rnbin && ./build.sh
  post_build:
    commands:
      - echo $GOPATH
      - cp /go/src/github.com/reiki4040/rnbin/rnbin .

artifacts:
  type: zip
  files:
    - rnbin
