version: 0.1

phases:
  install:
    commands:
      - go get github.com/Masterminds/glide
  pre_build:
    commands:
      - git checkout feature/aws_codebuild
      - glide up
  build:
    commands:
      - ./build.sh
  post_build:
    commands:
      - ls -l
artifacts:
  type: zip
  files:
    - rnbin
