version: 0.1

phases:
  install:
    commands:
      - go get github.com/Masterminds/glide
  pre_build:
    commands:
      - git checkout feature/aws_codebuild
      - glide up
      - mkdir -p $GOPATH/src/github.com/reiki4040/rnbin
      - mv * $GOPATH/src/github.com/reiki4040/rnbin/
  build:
    commands:
      - cd $GOPATH/src/github.com/reiki4040/rnbin && go build -o "rnbin"
  post_build:
    commands:
      - echo $GOPATH
      - ls -l $GOPATH/src/github.com/reiki4040/rnbin

artifacts:
  type: zip
  files:
    - rnbin
